"""Slides about streaming, chat state and artifact delivery."""
def add_streaming(add, head, diagram, table, flow, cards, takeaway, art):
    add('Streaming chat and artifacts','E',5,head('E','Streaming chat<br>and <em>artifacts</em>')+
        '<div class="comic-labels"><div><strong>Tool activity</strong><span>Show what the app is doing</span></div><div><strong>Streaming text</strong><span>Render the response as it arrives</span></div><div><strong>Artifacts</strong><span>Preview and download saved output</span></div></div>'+art('agent-streaming-comic.png','A robot looks up information, streams message updates, and delivers a report for review.','comic-image'),
        'Use the three panels to introduce separate UI responsibilities. Streaming reduces the wait before visible output; it does not guarantee faster total execution. A tool may run for some time without text, so show a real status event. An artifact is a saved output such as a report, CSV or image. The chapter describes a web application extension; the runnable terminal demo waits for a complete answer. Ask what users should see during a 30-second document lookup.')
    add('Streaming response architecture','E',6,head('E','Streaming response<br><em>architecture</em>')+diagram([
        (5,45,240,76,'Browser','Submit a user message','#d9e9f0'),(340,45,250,76,'API','Authenticate and start run','#d3ead7'),(735,45,260,76,'Agent / model','Produce events and text','#fbd8c9'),
        (735,235,260,70,'Run state','Messages and event IDs','#e4ece0')
    ],['M245 73H338','M590 73H733','M735 98H592','M340 98H247','M865 121V233'],
    'The browser submits a message to the API, which starts the agent. Events flow back through the API to the browser; the backend persists run state.')+
    '<p class="diagram-caption">Request → agent · streamed events → API → browser · persisted state for recovery</p>',
    'Explain two directions: the browser sends a request, then receives many updates. The API adapts provider or framework events to an application event format. It retains credentials server-side and filters internal or sensitive tool data before delivery. A separate worker needs an event channel back to the API, such as a broker or database-backed event log. Configure application and proxy layers to flush data rather than buffer the complete response. A saved run can continue after a browser disconnect, depending on the app policy.',sources=('streams','deep-streaming'))
    add('HTTP streaming, SSE and WebSockets','E',4,head('E','Streaming <em>transports</em>')+table(['Transport','Common use','Application responsibility'],[
        ('Fetch response stream','POST a prompt and read response chunks','Parse complete events; handle cancellation.'),
        ('Server-sent events (SSE)','Server sends named events over HTTP','Provide event IDs and replay if needed.'),
        ('WebSocket','Two-way messages on one connection','Manage connection state and reconnects.')
    ])+'<p class="mini-note">SSE is an event format; a fetch response can carry SSE.</p>',
    'These options overlap. Native EventSource opens a GET stream, so a common design creates a run with POST and subscribes using its run ID. A POST fetch can also return SSE data, but the client then parses the stream and manages reconnect logic. EventSource has built-in reconnection behavior; that alone does not persist or replay application events. WebSocket is useful when frequent bidirectional messages are needed. Plain polling remains a valid option for coarse job status. Recommend a single HTTP streaming approach for a first text-chat application.',sources=('sse','streams'))
    add('Application stream events','E',5,head('E','Application <em>events</em>')+table(['Example event','Meaning','UI update'],[
        ('run.started','Backend accepted the run','Show pending state.'),
        ('message.delta','More text for one message','Append to that message.'),
        ('tool.started / tool.finished','A tool changed state','Update its activity indicator.'),
        ('artifact.ready','A saved output is available','Show an artifact card.'),
        ('run.completed / failed / cancelled','The run reached a final state','Stop the indicator; show the outcome.')
    ],'event-table')+'<p class="mini-note">Example application schema · run_id, message_id, event_id, type, payload</p>',
    'These names are a teaching schema, not SDK event names. A transport chunk may contain part of one event or several events; decode and buffer before parsing. Keep stable identifiers so tool events, messages and artifacts are not mixed between runs. Order events and discard duplicates when replaying. A final completion event is distinct from the last text delta and from an unexpectedly closed connection. A provider may expose other events, which the backend should map before sending to the browser.')
    add('Chat and artifact rendering','E',6,head('E','Chat and artifact<br><em>rendering</em>')+
    '<div class="chat-artifact-layout"><div class="ui-chat"><div class="ui-bar">Conversation <span>Run complete</span></div><div class="ui-user">Compare the three reports.</div><div class="ui-tool">✓ Read 3 reports</div><div class="ui-assistant">The reports agree on demand growth. Their cost estimates differ. <span class="ui-citations">[1] [2] [3]</span></div><div class="ui-artifact-card"><b>Briefing · v1</b><span>Markdown · ready to preview</span></div></div><div class="ui-document"><div class="ui-bar">Artifact preview <span>Version 1</span></div><h3>Document briefing</h3><h4>Summary</h4><p>Demand is increasing across all three regions.</p><h4>Open questions</h4><p>Confirm the assumptions behind the cost estimates.</p><div class="ui-actions"><span>Download</span><span>Review</span></div></div></div>'+
    '<p class="diagram-caption">Example UI · conversation, tool status, citations and artifact preview are separate elements.</p>',
    'This is a static mockup; the displayed controls are illustrations. Append chunks to the same assistant message, not a new bubble per chunk. Render plain text safely or use a Markdown renderer that handles incomplete code blocks, links and tables. Disable or sanitize raw HTML. Batch visual updates and auto-scroll only when the reader is already near the bottom. Preserve scroll position when someone reads earlier content. Expose concise status updates for accessibility rather than announcing every token. Keep tool activity separate from answer text; do not expose hidden reasoning or credentials. The artifact opens in a separate preview with its own identity and version.')
    add('Message and run lifecycle','E',4,head('E','Message and run<br><em>lifecycle</em>')+flow([
        ('1','Submitted','Create stable message and run IDs.'),('2','In progress','Append text and show tool status.'),('3','Final state','Completed, failed or cancelled.')
    ])+table(['Store durably','Keep in frontend state'],[('Conversation, final messages, run status, artifact metadata','Current text buffer, selected preview, scroll position')]),
    'Distinguish a conversation from a run: one conversation contains multiple messages, and one run may involve multiple tools and model calls. A message can have partial content while the run is active. Keep partial output clearly marked if execution fails. Persistence supports refresh; local UI state alone does not. A cache can accelerate access but should not be the only copy of a completed conversation. Store replayable events when resuming a stream is a requirement; otherwise reload the latest saved state.')
    add('Artifact storage and delivery','E',5,head('E','Artifact storage<br>and <em>delivery</em>')+diagram([
        (0,35,230,76,'Agent / worker','Creates report content','#fbd8c9'),(310,35,230,76,'Object storage','Stores file bytes','#e4ece0'),(640,35,245,76,'Database','Owner, file key, version','#e4ece0'),
        (640,232,245,76,'Authorized API','Checks the viewer','#d3ead7'),(0,232,230,76,'Browser preview','Render or download','#d9e9f0')
    ],['M230 73H308','M540 73H638','M762 111V230','M640 270H232'],
    'The worker saves file bytes in object storage and metadata in a database. An authorized API makes the completed artifact available to the browser.')+
    '<p class="diagram-caption">Publish artifact.ready after the file and metadata are saved.</p>',
    'An artifact is a durable output, not merely a long chat message. Store content type, size, owner, status and version. The arrows show a lifecycle, not a claim that object storage writes database records itself; backend code coordinates both writes. Return an authorized download endpoint or a short-lived signed URL after checking ownership. Use safe renderers for Markdown, CSV and images. Treat generated HTML as untrusted; sandbox previews and restrict scripts and network access. Use a new version for revisions so review applies to a specific artifact.',sources=('fastapi-responses',))
    add('Cancellation and reconnects','E',5,head('E','Cancellation<br>and <em>reconnects</em>')+table(['Situation','Expected behavior'],[
        ('User selects Stop','Cancel the reader and request backend cancellation.'),
        ('Connection drops','Show disconnected state; reload status or replay events.'),
        ('Client retries a request','Reuse an idempotency key to avoid duplicate work.'),
        ('Run fails after partial output','Keep the partial result marked incomplete; show retry.'),
        ('Artifact takes longer than chat','Track it as a job and show a separate completion event.')
    ]),
    'Aborting the browser fetch does not by itself guarantee that the server, model or worker stops. The backend must propagate cancellation and report the resulting state. Cancellation cannot undo side effects already committed. Reconnect with the same run ID; replay after the last event ID only if the backend retains events. If replay is unavailable, fetch a current snapshot rather than silently starting a duplicate run. For long tasks, persist job state outside the streaming connection. Ask participants to explain what a refresh should do during report generation.',sources=('streams','sse'))
